apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-k8s-app
  namespace: public
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-k8s-app
  template:
    metadata:
      labels:
        app: devops-k8s-app
    spec:
      containers:
      - name: devops-k8s-app
        image: swarajhegde/devops-k8s-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: devops-config
              key: APP_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: devops-config
              key: LOG_LEVEL
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: devops-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devops-secret
              key: DB_PASSWORD
