apiVersion: v1
kind: Service
metadata:
  name: devops-k8s-service
  namespace: public
spec:
  selector:
    app: devops-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
